name: Create Tagged Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: out/release

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/release/checksums.txt
            out/release/lampa-*
